//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailsOpacBase.Portails.Diagnostique
{
    using System;
    using System.Collections.Generic;
    
    public partial class diag_logement
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> iddiag { get; set; }
        public string gbal { get; set; }
        public string appt { get; set; }
        public Nullable<System.DateTime> datediag { get; set; }
        public bool valid { get; set; }
    }
}
