//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailsOpacBase.Portails.Diagnostique
{
    using System;
    using System.Collections.Generic;
    
    public partial class diag
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> iddiag { get; set; }
        public string numcommande { get; set; }
        public string nomsociete { get; set; }
        public string correspondant { get; set; }
        public string diagnostiqueur { get; set; }
        public Nullable<System.DateTime> daterapport { get; set; }
        public string groupe { get; set; }
        public string bati { get; set; }
        public string allee { get; set; }
        public Nullable<bool> export { get; set; }
        public string profil { get; set; }
        public Nullable<System.DateTime> datedepot { get; set; }
        public Nullable<int> type_diag { get; set; }
        public Nullable<int> type_parties { get; set; }
        public string type_energie_chauffage { get; set; }
        public string type_energie_ecs { get; set; }
        public Nullable<int> energie_consommation { get; set; }
        public string energie_etiquette { get; set; }
        public Nullable<int> ges_emissions { get; set; }
        public string ges_etiquettes { get; set; }
        public Nullable<int> surface { get; set; }
    }
}
