//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailsOpacBase.Portails.Diagnostique
{
    using System;
    using System.Collections.Generic;
    
    public partial class diag_logement_pieces
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> idligne { get; set; }
        public string piece { get; set; }
        public Nullable<bool> amiante { get; set; }
        public Nullable<int> prelevements { get; set; }
        public Nullable<System.Guid> groupe { get; set; }
        public string zone { get; set; }
        public string commentaires { get; set; }
        public string elements_traites { get; set; }
        public string nature_travaux { get; set; }
        public Nullable<bool> plomb { get; set; }
        public int numligne { get; set; }
    }
}
