//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailsOpacBase.Portails.Diagnostique
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiagnostiquesEntities : DbContext
    {
        public DiagnostiquesEntities()
            : base("name=DiagnostiquesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<diag_logement> diag_logement { get; set; }
        public virtual DbSet<diag_logement_pieces> diag_logement_pieces { get; set; }
        public virtual DbSet<diag_logement_fichiers> diag_logement_fichiers { get; set; }
        public virtual DbSet<diag> diag { get; set; }
        public virtual DbSet<connexions> connexions { get; set; }
    }
}
