//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeleteConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class connexions
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> idconnexion { get; set; }
        public string nom { get; set; }
        public string profil { get; set; }
        public Nullable<System.DateTime> dateheure { get; set; }
    }
}
